##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server:
  port: 8082
  connection-timeout: 180
  session:
    timeout: 180
    cookie:
      max-age: 180
      http-only: true
tool:
  ver: B2                       # 柜子版本
  tmpUploadPath: d:/tmp/        # 上传临时文件夹
  uploadPath: d:/upload/        # 附件存储路径
  iconsPath: d:/icons/          # excel上传时图片文件路径
  nettyServerHost: localhost    # netty服务端地址
  nettyServerPort: 9000         # netty服务端口
  mailHost: smtp.qq.com         # 邮箱服务器 
  mailProtocol: smtp            # 协议
  mailSender: 东             # 发送人
  mailAddr: 1878256577@qq.com   #发送邮箱
  mailAuthorCode: zqzzjphixxkbfbcd # 邮箱授权码
  verifyScanCOM: COM33   #扫描仪串口号（用于归还验证）
  digitalTubeCOM: COM12   #数码管串口号（用于扫码上架）
  
  
eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
###################  spring配置  ###################
spring:
  cloud:
    client: 
      ipAddress: localhost
  application:
    name: service-tool
  profiles:
    active: dev
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379
    password: 123
    timeout: 1800000  #单位毫秒,默认30分钟
    pool:
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
  mvc: 
    static-path-pattern: /static/**
  thymeleaf: 
    template-resolver-order: 2
    prefix: classpath:/templates
    suffix: 
    mode: HTML5
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    check-template: false
    encoding: UTF-8
  http: 
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  aop:
    proxy-target-class: false #false为启用jdk默认动态代理,true为cglib动态代理

---

##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tool?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
logging:
  level:
    root: info
    com.dosth: debug
  path: logs/

---

##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: produce
  datasource:
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://localhost:1433/tool
    username: sa
    password: 123
  jpa: 
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.dosth: info
    com.dosth.netty: info
  path: logs/
