##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  dosth配置  ###################
dosth: 
  dataCenterId: 444777 # 数据中心编号
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  file-tmp-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  sso:
    facePath: d:/upload/face
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  swagger-open: true #是否开启swagger (true/false)
###################  项目启动端口  ###################
server:
  port: 8081


eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true

###################  spring配置  ###################
spring:
  cloud:
    client:
      ipAddress: localhost
  application:
    name: service-admin
  profiles:
    active: mySql
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379
    password: 123
    database: 0 #默认使用db0  
    timeout: 1800000  #单位毫秒,默认30分钟
    pool:
      max-active: 8  
      max-wait: -1  
      max-idle: 8  
      min-idle: 0  
  mvc: 
    static-path-pattern: /static/**
  thymeleaf: 
    template-resolver-order: 2
    prefix: classpath:/templates
    suffix: 
    mode: HTML5
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    check-template: false
    encoding: UTF-8
  http: 
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools: 
    restart:
      enabled: true #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: false #false为启用jdk默认动态代理,true为cglib动态代理

    
######################### COM 串口配置(IC卡绑定用户功能)################
COM:
  ICCom: COM66
---

##########################################################
###################  mySql环境配置  ######################
##########################################################
spring:
  profiles: mySql
  datasource: 
      url: jdbc:mysql://localhost:3306/dosth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
---

##########################################################
###################  sqlServer环境配置  ##################
##########################################################
spring:
  profiles: sqlServer
  datasource:
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://localhost:1433/dosth
    username: sa
    password: 123
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

