server:
  address: localhost
  port: 8080
  
eureka: 
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
###################  spring配置  ###################
spring:
  application:
    name: service-app
  cloud:
    client: 
      ipAddress: ${server.address}
  mvc:
    static-path-pattern: /**