#创建人员信息视图
DROP VIEW IF EXISTS VIEW_USER;
CREATE VIEW VIEW_USER
AS
SELECT A.ID ACCOUNT_ID, U.DEPT_ID, U.NAME USER_NAME, A.LOGIN_NAME, U.IC_CARD, U.START_TIME, U.END_TIME, U.LIMIT_SUM_NUM, U.NOT_RETURN_LIMIT_NUM
FROM dosth.ACCOUNT A
LEFT JOIN dosth.USERS U
ON A.ID = U.ACCOUNT_ID
WHERE A.`status` = 'OK';

#创建部门视图
DROP VIEW IF EXISTS VIEW_DEPT;
CREATE VIEW VIEW_DEPT
AS
SELECT D.ID DEPT_ID, D.P_ID DEPT_P_ID, D.DEPT_NAME, D.`status` DEPT_STATUS FROM dosth.DEPT D;