# 数据源
spring:
   datasource:
      default:
         url: jdbc:mysql://192.168.2.78:3306/bsc-tool-box-drawer?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         username: root
         password: 123456
      outer:
         url: jdbc:mysql://192.168.2.78:3306/test-mes?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         username: root
         password: 123456
