# 数据源
spring:
   datasource:
      default:
         url: jdbc:mysql://192.168.8.78:3306/bsc-tool-box-drawer?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         username: root
         password: 123456
      outer:
         url: jdbc:sqlserver://192.168.8.78:2225;DatabaseName=ANUOMES
         driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
         username: slz
         password: slz123456
