USE tool;
GO
--创建人员信息视图
IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME = 'VIEW_USER')
DROP VIEW VIEW_USER;
GO
CREATE VIEW VIEW_USER
AS
SELECT A.ID ACCOUNT_ID, U.DEPT_ID, U.NAME USER_NAME, A.LOGIN_NAME
FROM dosth.dbo.ACCOUNT A
LEFT JOIN dosth.dbo.USERS U
ON A.ID = U.ACCOUNT_ID;
GO
--创建部门视图
IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME = 'VIEW_DEPT')
DROP VIEW VIEW_DEPT;
GO
CREATE VIEW VIEW_DEPT
AS
SELECT D.ID DEPT_ID, D.P_ID DEPT_P_ID, D.SIMPLE_NAME DEPT_NAME FROM dosth.dbo.DEPT D;